# Generated by Django 4.2.1 on 2023-05-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('std_number', models.IntegerField()),
                ('teacher', models.CharField(choices=[('ahmadi', 'AHMADI'), ('abdi', 'ABDI'), ('bahrami', 'BAHRAMI')], max_length=7)),
            ],
        ),
    ]
